export const GET_ADMIN = "GET_ADMIN"
export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS"
export const CREATE_ADMIN = "CREATE_ADMIN"
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS"
export const DELETE_ADMIN = "DELETE_ADMIN"
export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS"

export const API_ERROR = "API_ERROR"