export const GET_CONTENT = 'GET_CONTENT';
export const GET_CONTENT_SUCCESS = 'GET_CONTENT_SUCCESS';
export const DELETE_CONTENT = 'DELETE_CONTENT';
export const DELETE_CONTENT_SUCCESS = 'DELETE_CONTENT_SUCCESS';
export const GET_CONTENT_DETAILS = 'GET_CONTENT_DETAILS';
export const GET_CONTENT_DETAILS_SUCCESS = 'GET_CONTENT_DETAILS_SUCCESS';

export const API_ERROR = 'API_ERROR';
