export const FAN_PUSH_NOTIFICATIONS = 'FAN_PUSH_NOTIFICATIONS';
export const FAN_PUSH_NOTIFICATIONS_SUCCESS = 'FAN_PUSH_NOTIFICATIONS_SUCCESS';
export const SINGLE_FAN_NOTIFICATION = 'SINGLE_FAN_NOTIFICATION';
export const SINGLE_FAN_NOTIFICATION_SUCCESS = 'SINGLE_FAN_NOTIFICATION_SUCCESS';

export const API_ERROR = 'API_ERROR';
