export const SEND_PUSH_NOTIFICATIONS = 'SEND_PUSH_NOTIFICATIONS';
export const SEND_PUSH_NOTIFICATIONS_SUCCESS = 'SEND_PUSH_NOTIFICATIONS_SUCCESS';
export const SINGLE_NOTIFICATION = 'SINGLE_NOTIFICATION';
export const SINGLE_NOTIFICATION_SUCCESS = 'SINGLE_NOTIFICATION_SUCCESS';

export const API_ERROR = 'API_ERROR';
