export const GET_BLOCKED_USERS = 'GET_BLOCKED_USERS';
export const GET_BLOCKED_USERS_SUCCESS = 'GET_BLOCKED_USERS_SUCCESS';
export const UNBLOCK_USER = 'UNBLOCK_USER';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';

export const API_ERROR = 'API_ERROR';
