export const GET_CELEBRITY = 'GET_CELEBRITY';
export const GET_CELEBRITY_SUCCESS = 'GET_CELEBRITY_SUCCESS';
export const GET_SINGLE_CELEBRITY = 'GET_SINGLE_CELEBRITY';
export const GET_SINGLE_CELEBRITY_SUCCESS = 'GET_SINGLE_CELEBRITY_SUCCESS';
export const CREATE_CELEBRITY = 'CREATE_CELEBRITY';
export const CREATE_CELEBRITY_SUCCESS = ' CREATE_CELEBRITY_SUCCESS';
export const BLOCK_CELEBRITY = 'BLOCK_CELEBRITY';
export const BLOCK_CELEBRITY_SUCCESS = ' BLOCK_CELEBRITY_SUCCESS';

export const API_ERROR = 'API_ERROR';
