export const GET_STORIES = 'GET_STORIES';
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';
export const GET_SINGLE_STORY = 'GET_SINGLE_STORY';
export const GET_SINGLE_STORY_SUCCESS = 'GET_SINGLE_STORY_SUCCESS';
export const DELETE_STORY = 'DELETE_STORY';
export const DELETE_STORY_SUCCESS = 'DELETE_STORY_SUCCESS';
export const DELETE_SINGLE_STORY = 'DELETE_SINGLE_STORY';
export const DELETE_SINGLE_STORY_SUCCESS = 'DELETE_SINGLE_STORY_SUCCESS';


export const API_ERROR = 'API_ERROR';
