export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"

export const VERIFY_LOGIN = "VERIFY_LOGIN"
export const VERIFY_USER_LOGIN = "VERIFY_USER_LOGIN"

export const REVERIFY_LOGIN = "REVERIFY_LOGIN"
export const REVERIFY_USER_LOGIN = "REVERIFY_USER_LOGIN"

export const API_ERROR = "LOGIN_API_ERROR"